service: boy-yah-middleware
provider:
  name: aws
  runtime: nodejs10.x
  apiGateway:
    minimumCompressionSize: 1024
  stage: ${opt:stage, 'dev'}
  region: eu-west-2

  environment:
    API_ENDPOINT: ${env:API_ENDPOINT}

functions:
  handler:
    handler: src/index.handler
    name: ${opt:stage, 'dev'}-middleware-boy-yah
    events:
      - http:
          method: GET
          path: /{lol}
          private: false
          cors: true
      - http:
          method: POST
          path: /{lol}
          private: false
          cors: true

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: "./config/webpack.js"
    includeModules: true
    packager: "yarn"
